# Change the default logo inside the webmail and on the login screen
# This playbook is not required to run for a 100% install. To skip, just don't
# inform the vars zmlogologin and zmlogoapp.
#  WARNING: It's required to use this playbook both files: The logo for the
#           webmail and the logo for the login screen.

- name: Send the logo files from your PC to the Server
  copy:
    src: '{{ src }}'
    dest: "{{ zimbra_home }}/jetty/webapps/zimbra/img/logo{{ name }}Banner.png"
    owner: "{{ zimbra_user }}"
    group: "{{ zimbra_group }}"
    mode: 0644
  with_items: "{{ zimbra_logos }}"

- name: Configure the Zimbra Server to find the new logos
  command: './zmprov md {{ domain }} zimbraSkinLogoURL https://{{ hostname }}.{{ domain }}'
  args:
    chdir: "{{ zimbra_bin }}"
  become: yes
  become_user: "{{ zimbra_user }}"

- name: Configure the path for the logo files
  command: './zmprov md {{ domain }} zimbraSkinLogoLoginBanner /img/logo{{ name }}Banner.png'
  args:
    chdir: "{{ zimbra_bin }}"
  with_items: "{{ zimbra_logos }}"
  become: yes
  become_user: "{{ zimbra_user }}"
