---
#
# Install PolicyD
################################################################################
- name: Installing PolicyD Service
  command: ./zmprov ms "{{ hostname }}"."{{ domain }}" +zimbraServiceInstalled cbpolicyd +zimbraServiceEnabled cbpolicyd
  args:
    chdir: "{{ zimbra_bin }}"
