---
#
# Configuring Zimbra OSE
################################################################################
- name: Querying DKIM records for domain
  command: /opt/zimbra/libexec/zmdkimkeyutil -q -d "{{ domain }}"
  register: dkim_result
  become: true
  become_user: zimbra

- name: Add DKIM data for domain
  command: /opt/zimbra/libexec/zmdkimkeyutil -a -d "{{ domain }}"
  when: dkim_result.rc == 1
  become: true
  become_user: zimbra