---
#
# Configuring Zimbra OSE
################################################################################
- name: Enabling HTTP to HTTPS redirect
  command: ./zmprov ms "{{ hostname }}"."{{ domain }}" zimbraReverseProxyMailMode redirect
  args:
    chdir: "{{ zimbra_bin }}"

- name: Setting LMTP Host Lookup from DNS to Native
  command: ./zmprov mcf zimbraMtaLmtpHostLookup native
  args:
    chdir: "{{ zimbra_bin }}"

#
# Configuring RBLs
################################################################################
- name: Importing RBLs
  command: ./zmprov ms "{{ hostname }}"."{{ domain }}" +zimbraMtaRestriction 'reject_rbl_client {{ item }}'
  args:
    chdir: "{{ zimbra_bin }}"
  with_items: "{{ zimbra_rbls }}"
  become: yes
  become_user: "{{ zimbra_user }}"